# Generated by Django 4.2.18 on 2025-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userService", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
